<?php
// public/install/index.php
// Web Installer for Red Cross Radio Simulation

$configFile = null;
$schemaFile = null;

// Determine paths for flat (cPanel) or nested (Dev) structure
if (file_exists(__DIR__ . '/../config/db.php')) {
    // Flat: public_html/install/index.php -> public_html/config/db.php
    $configFile = __DIR__ . '/../config/db.php';
} elseif (file_exists(__DIR__ . '/../../config/db.php')) {
    // Nested: public/install/index.php -> ../config/db.php
    $configFile = __DIR__ . '/../../config/db.php';
} else {
    // Attempt creation in flat structure by default if dir exists
    if (is_dir(__DIR__ . '/../config')) {
        $configFile = __DIR__ . '/../config/db.php';
    } else {
        // Create dir if possible? Usually not writable. Assume flat.
        $configFile = __DIR__ . '/../config/db.php';
    }
}

if (file_exists(__DIR__ . '/../database.sql')) {
    $schemaFile = __DIR__ . '/../database.sql';
} elseif (file_exists(__DIR__ . '/../../database.sql')) {
    $schemaFile = __DIR__ . '/../../database.sql';
}

// Check if already installed
if ($configFile && file_exists($configFile)) {
    $installed = true;
} else {
    $installed = false;
}

$message = '';
$error = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $host = $_POST['host'] ?? 'localhost';
    $name = $_POST['name'] ?? '';
    $user = $_POST['user'] ?? '';
    $pass = $_POST['pass'] ?? '';

    $adminUser = $_POST['admin_user'] ?? 'admin';
    $adminPass = $_POST['admin_pass'] ?? 'admin123';
    $adminEmail = $_POST['admin_email'] ?? 'admin@cruzroja.org';

    $signalUrl = $_POST['signal_url'] ?? '';

    if (empty($name) || empty($user) || empty($adminUser) || empty($adminPass)) {
        $message = "Please fill all required fields.";
        $error = true;
    } else {
        try {
            // 1. Test Connection
            $dsn = "mysql:host=$host;dbname=$name;charset=utf8mb4";

            // Testing Override
            if (getenv('APP_ENV') === 'local_test') {
                $dsn = "sqlite:" . __DIR__ . '/../../database.sqlite';
            }

            $options = [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            ];
            $pdo = new PDO($dsn, $user, $pass, $options);

            // 2. Read Schema
            if (!$schemaFile || !file_exists($schemaFile)) {
                throw new Exception("Schema file database.sql not found!");
            }
            $schema = file_get_contents($schemaFile);

            // 3. Execute Schema
            if (getenv('APP_ENV') !== 'local_test') {
                $pdo->exec("SET FOREIGN_KEY_CHECKS=0");
            } else {
                $schema = str_replace('INT AUTO_INCREMENT PRIMARY KEY', 'INTEGER PRIMARY KEY AUTOINCREMENT', $schema);
                $schema = str_replace('TIMESTAMP DEFAULT CURRENT_TIMESTAMP', 'DATETIME DEFAULT CURRENT_TIMESTAMP', $schema);
            }

            $statements = explode(';', $schema);
            foreach ($statements as $sql) {
                if (trim($sql)) {
                    try {
                        $pdo->exec($sql);
                    } catch (PDOException $e) {
                        // Ignore existing
                    }
                }
            }

            // 4. Create/Update Admin User
            $pdo->exec("DELETE FROM users WHERE username = 'admin' OR role_id = 1");

            $stmt = $pdo->prepare("SELECT id FROM roles WHERE name = 'admin'");
            $stmt->execute();
            $roleId = $stmt->fetchColumn();

            if (!$roleId) {
                 $pdo->exec("INSERT INTO roles (name, description) VALUES ('admin', 'Administrator'), ('student', 'Student'), ('operator', 'Operator')");
                 $roleId = $pdo->lastInsertId();
            }

            $hash = password_hash($adminPass, PASSWORD_DEFAULT);
            $stmt = $pdo->prepare("INSERT INTO users (username, email, password_hash, role_id) VALUES (?, ?, ?, ?)");
            $stmt->execute([$adminUser, $adminEmail, $hash, $roleId]);

            // 5. Write Config File
            // Ensure dir exists
            $configDir = dirname($configFile);
            if (!is_dir($configDir)) mkdir($configDir, 0755, true);

            $configContent = "<?php\n" .
                             "// config/db.php\n" .
                             "// Auto-generated by Installer\n\n" .
                             "\$host = " . var_export($host, true) . ";\n" .
                             "\$db   = " . var_export($name, true) . ";\n" .
                             "\$user = " . var_export($user, true) . ";\n" .
                             "\$pass = " . var_export($pass, true) . ";\n" .
                             "\$charset = 'utf8mb4';\n\n" .
                             "\$dsn = \"mysql:host=\$host;dbname=\$db;charset=\$charset\";\n\n" .
                             "\$options = [\n" .
                             "    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,\n" .
                             "    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,\n" .
                             "    PDO::ATTR_EMULATE_PREPARES   => false,\n" .
                             "];\n\n" .
                             "try {\n" .
                             "    \$pdo = new PDO(\$dsn, \$user, \$pass, \$options);\n" .
                             "} catch (\PDOException \$e) {\n" .
                             "    error_log(\$e->getMessage());\n" .
                             "    die(\"Database connection failed. Please check config/db.php.\");\n" .
                             "}\n" .
                             "?>";

            if (file_put_contents($configFile, $configContent) === false) {
                 throw new Exception("Could not write to config/db.php. Check permissions.");
            }

            // 6. Handle Signaling URL
            if ($signalUrl) {
                $jsConfig = "window.SIGNALING_SERVER_CONFIG = " . var_export($signalUrl, true) . ";";
                // Try flat path first
                $jsPath = __DIR__ . '/../js/config.js';
                if (!is_dir(dirname($jsPath))) {
                     // Try nested
                     $jsPath = __DIR__ . '/../../public/js/config.js';
                }
                // Ensure js dir exists if flat path chosen
                if (!is_dir(dirname($jsPath))) mkdir(dirname($jsPath), 0755, true);

                file_put_contents($jsPath, $jsConfig);
            }

            $message = "Installation Successful! <a href='../index.php'>Go to Login</a>";
            $installed = true;

        } catch (Exception $e) {
            $message = "Error: " . $e->getMessage();
            $error = true;
        }
    }
}
?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cruz Roja - Instalador Web</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <style>
        body { font-family: 'Roboto', sans-serif; background: #f7f7f7; color: #333; display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; }
        .container { width: 100%; max-width: 500px; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); border-top: 5px solid #ce1126; }
        h2 { color: #ce1126; margin-top: 0; text-align: center; }
        label { display: block; margin-top: 15px; font-weight: bold; font-size: 0.9em; }
        input { width: 100%; padding: 10px; margin-top: 5px; border: 1px solid #ddd; border-radius: 4px; box-sizing: border-box; }
        button { width: 100%; padding: 12px; background: #ce1126; color: white; border: none; border-radius: 4px; font-size: 1em; font-weight: bold; margin-top: 20px; cursor: pointer; transition: background 0.3s; }
        button:hover { background: #a60e1e; }
        .alert { padding: 15px; margin-bottom: 20px; border-radius: 4px; font-size: 0.9em; }
        .alert.error { background: #ffebee; color: #b71c1c; border: 1px solid #ffcdd2; }
        .alert.success { background: #e8f5e9; color: #1b5e20; border: 1px solid #c8e6c9; }
        small { color: #666; font-size: 0.8em; }
    </style>
</head>
<body>

<div class="container">
    <h2>Instalador del Sistema</h2>

    <?php if ($message): ?>
        <div class="alert <?= $error ? 'error' : 'success' ?>">
            <?= $message ?>
        </div>
    <?php endif; ?>

    <?php if (!$installed || $error): ?>
    <form method="POST">
        <h3>1. Base de Datos (MySQL)</h3>
        <label>Host (Servidor)</label>
        <input type="text" name="host" placeholder="localhost" value="localhost" required>

        <label>Nombre de la Base de Datos</label>
        <input type="text" name="name" placeholder="cruzroja_db" required>

        <label>Usuario DB</label>
        <input type="text" name="user" placeholder="root" required>

        <label>Contraseña DB</label>
        <input type="password" name="pass" placeholder="">

        <h3>2. Cuenta Administrador</h3>
        <label>Usuario Admin</label>
        <input type="text" name="admin_user" value="admin" required>

        <label>Contraseña Admin</label>
        <input type="password" name="admin_pass" required>

        <label>Email Admin</label>
        <input type="email" name="admin_email" value="admin@cruzroja.org" required>

        <h3>3. Configuración Adicional</h3>
        <label>URL Servidor Señalización (Node.js)</label>
        <input type="text" name="signal_url" placeholder="https://tu-dominio.com/radio-signal">
        <small>Dejar en blanco si configurará manualmente o usará el puerto por defecto.</small>

        <button type="submit">Instalar Sistema</button>
    </form>
    <?php else: ?>
        <div style="text-align: center;">
            <p>El sistema ya está instalado.</p>
            <a href="../index.php"><button>Ir al Login</button></a>
        </div>
    <?php endif; ?>
</div>

</body>
</html>
